### ISSUE TITLE
Getting error While Compiling

### ISSUE THREAD

**Issue by MandySingh3** [XOSP/android_system_core#2]
Generating master DTB... completed
Made DT image: /home/mr_singh/xosp/out/target/product/potter/dt.img
[  2% 545/22779] Target buildinfo: /home/mr_singh/xosp/out/target/product/potter/obj/ETC/system_build_prop_intermediates/build.prop
Target buildinfo from: device/motorola/potter/system.prop
[  2% 547/22779] target thumb C++: libhealthd_internal <= system/core/healthd/healthd_mode_charger.cpp
FAILED: /bin/bash -c "(PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-2690385/bin/clang++ -I device/motorola/potter/include -I bootable/recovery -I system/core/healthd -I /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates -I /home/mr_singh/xosp/out/target/product/potter/gen/STATIC_LIBRARIES/libhealthd_internal_intermediates -I libnativehelper/include/nativehelper \$(cat /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/import_includes) -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem hardware/ril/include -isystem /home/mr_singh/xosp/out/target/product/potter/obj/include -isystem bionic/libc/arch-arm/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/common -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libm/include -isystem bionic/libm/include/arm -c    -fno-exceptions -Wno-multichar -msoft-float -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -mcpu=cortex-a7 -D__ARM_FEATURE_LPAE=1 -mfloat-abi=softfp -mfpu=neon -DQCOM_HARDWARE -DQCOM_BSP -DQTI_BSP -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -DNDEBUG -g -Wstrict-aliasing=2 -DNDEBUG -UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -nostdlibinc  -target arm-linux-androideabi    -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin    -fvisibility-inlines-hidden -DQCOM_HARDWARE -DQCOM_BSP -DQTI_BSP -Wsign-promo  -Wno-inconsistent-missing-override -nostdlibinc  -target arm-linux-androideabi   -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing  -fno-rtti -DCHARGER_ENABLE_SUSPEND -fPIC -D_USING_LIBCXX -std=gnu++14  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast  -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type    -MD -MF /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.d -o /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.o system/core/healthd/healthd_mode_charger.cpp ) && (cp /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.d /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$//' -e '/^\$/ d' -e 's/\$/ :/' < /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.d >> /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.P; rm -f /home/mr_singh/xosp/out/target/product/potter/obj/STATIC_LIBRARIES/libhealthd_internal_intermediates/healthd_mode_charger.d )"
system/core/healthd/healthd_mode_charger.cpp:388:33: error: use of undeclared identifier 'gr_sys_font'
    int str_len_px = gr_measure(gr_sys_font(), str);
                                ^
system/core/healthd/healthd_mode_charger.cpp:394:13: error: use of undeclared identifier 'gr_sys_font'
    gr_text(gr_sys_font(), x, y, str, 0);
            ^
system/core/healthd/healthd_mode_charger.cpp:410:41: error: member access into incomplete type 'GRFont'
    int str_len_px = length * field.font->char_width;
                                        ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:420:42: error: member access into incomplete type 'GRFont'
        *y = (gr_fb_height() - field.font->char_height) / 2;
                                         ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:424:55: error: member access into incomplete type 'GRFont'
        *y = gr_fb_height() + field.pos_y - field.font->char_height;
                                                      ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:435:44: error: member access into incomplete type 'GRFont'
    if (field.font == nullptr || field.font->char_width == 0 || field.font->char_height == 0) return;
                                           ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:453:5: error: no matching function for call to 'gr_text'
    gr_text(field.font, x, y, clock_str, false);
    ^~~~~~~
bootable/recovery/minui/minui.h:49:6: note: candidate function not viable: requires 4 arguments, but 5 were provided
void gr_text(int x, int y, const char *s, bool bold);
     ^
system/core/healthd/healthd_mode_charger.cpp:466:44: error: member access into incomplete type 'GRFont'
    if (field.font == nullptr || field.font->char_width == 0 || field.font->char_height == 0) {
                                           ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:477:5: error: no matching function for call to 'gr_text'
    gr_text(field.font, x, y, str.c_str(), false);
    ^~~~~~~
bootable/recovery/minui/minui.h:49:6: note: candidate function not viable: requires 4 arguments, but 5 were provided
void gr_text(int x, int y, const char *s, bool bold);
     ^
system/core/healthd/healthd_mode_charger.cpp:558:17: error: use of undeclared identifier 'gr_init_font'
                gr_init_font(anim->text_clock.font_file.c_str(), &anim->text_clock.font)) < 0) {
                ^
system/core/healthd/healthd_mode_charger.cpp:565:17: error: use of undeclared identifier 'gr_init_font'
                gr_init_font(anim->text_percent.font_file.c_str(), &anim->text_percent.font)) < 0) {
                ^
system/core/healthd/healthd_mode_charger.cpp:591:22: error: use of undeclared identifier 'gr_sys_font'
        gr_font_size(gr_sys_font(), &char_width, &char_height);
                     ^
12 errors generated.
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

**Comment by nilac8991** [comment]
7.1.2 merge is in progress. ROM is not compilable
